const REACTION_CHOICES: { value: string; label: string }[] = [
    { value: '😍', label: 'Heart eyes' },
    { value: '🥰', label: 'Smiling face with hearts' },
    { value: '🤩', label: 'Star-struck' },
    { value: '🤗', label: 'Hugging face' },
    { value: '😂', label: 'Face with tears of joy' },
    { value: '🤣', label: 'Rolling on the floor laughing' },
    { value: '😅', label: 'Grinning face with sweat' },
    { value: '😁', label: 'Grinning face with smiling eyes' },
    { value: '🙄', label: 'Face with rolling eyes' },
    { value: '😏', label: 'Smirking face' },
    { value: '😴', label: 'Sleeping face' },
    { value: '😜', label: 'Winking face with tongue' },
    { value: '🤐', label: 'Zipper-mouth face' },
    { value: '😲', label: 'Astonished face' },
    { value: '😤', label: 'Face with steam from nose' },
    { value: '🤯', label: 'Exploding head' },
    { value: '😡', label: 'Pouting face' },
    { value: '😠', label: 'Angry face' },
    { value: '😵', label: 'Dizzy face' },
    { value: '😈', label: 'Smiling face with horns' },
    { value: '🙈', label: 'See-no-evil monkey' },
    { value: '🙊', label: 'Speak-no-evil monkey' },
    { value: '🙉', label: 'Hear-no-evil monkey' },
    { value: '👀', label: 'Eyes' },
    { value: '❤️', label: 'Red heart' },
    { value: '💔', label: 'Broken heart' },
    { value: '🆘', label: 'SOS' },
    { value: '🙆🏾‍♂️', label: 'Man raising hand' },
    { value: '🙆🏾‍♀️', label: 'Woman raising hand' },
    { value: '💪🏾', label: 'Flexed biceps' },
    { value: '🙏🏾', label: 'Folded hands' },
];

export default REACTION_CHOICES